{% set name = "scine-database-python" %}
{% set version = "1.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/qcscine/database/archive/refs/tags/{{ version }}.tar.gz
    sha256: 23a7b1cfb7c4e8df2fac70d77d0e9b0ddfffaeb64496a614408db4a564b15703
    patches:
      - skip_library_build.patch
  - url: https://github.com/qcscine/development-utils/archive/refs/tags/5.0.0.tar.gz
    sha256: bb2f161ed15811def85ca635924427356564a811779993123077f4ada048be84
    folder: dev
    patches:
      - pybind11_pin.patch

build:
  number: 0
  skip: true  # [win]
  skip: true  # [osx]
  ignore_run_exports:
    - libblas

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - eigen
    # Needed for eigen detection
    - libblas
    - pip
    - pybind11
    - pybind11-abi
    - python
    - scine-database {{ version }}
  run:
    - python
    - scine-database {{ version }}
    - scine-utilsos
    - scine-utilities-python

test:
  imports:
    - scine_database
  source_files:
    - src/Database/Python/Tests/
  requires:
    - pip
    - pytest

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: |
    The SCINE database module is a database wrapper for a MongoDB encoding reaction networks
    (Python bindings).
  home: https://scine.ethz.ch/
  dev_url: https://github.com/qcscine/database

extra:
  recipe-maintainers:
    - awvwgk
